In [1]:
import numpy as np

In [2]:
a = np.array(
[
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b =a.sum(axis = 1)
b

array([ 6, 15, 24])

In [5]:
np.array([b])

array([[ 6, 15, 24]])

In [7]:
c = np.array([[1],[1],[1]])
c

array([[1],
       [1],
       [1]])

In [8]:
np.dot(a,c)

array([[ 6],
       [15],
       [24]])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a.sum(axis=0)

array([12, 15, 18])

In [11]:
d = np.array(
[
    [1,1,1]
])
d

array([[1, 1, 1]])

In [12]:
np.dot(d,a)

array([[12, 15, 18]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
a - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [16]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [17]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [18]:
e = np.array([1,2,3])
e

array([1, 2, 3])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a / e

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
f = np.array([
    [1],
    [2],
    [3],
])
f

array([[1],
       [2],
       [3]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a / f

array([[1.        , 2.        , 3.        ],
       [2.        , 2.5       , 3.        ],
       [2.33333333, 2.66666667, 3.        ]])