In [1]:
print(123)

123


# Markdown一级标题
## Markdown二级标题

In [5]:
%run ./test.py

Hello World


In [7]:
# %load ./test.py
print('Hello World')

def my_print(x):
	print(x)

Hello World


In [8]:
my_print("Hi")

Hi


In [10]:
from test import my_print
my_print("Hi import")

Hi import


In [11]:
# notebook对同一文件只会导入一次
# 导入的文件修改后需要重新%run
%run ./test.py

Hello World


In [14]:
# 运行一千次，求了一千次的平均时间
# 程序运行时间少，所以需要N次运行减少进程调度切换等的时间影响 
%timeit li = [i**2 for i in range(1000)]

324 µs ± 5.89 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
# 运行了一次，程序运行时间长，所以进程调度切换的时间影响小
%timeit li = [i**2 for i in range(1000000)]

343 ms ± 5.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
# %%timeit 测试代码块
%%timeit
li = []
for i in range(1000):
    li.append(i**2)
# 在python中使用列表生成式比for高效

370 µs ± 4.83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
import random
li = [random.random() for i in range(100000)]
%timeit li.sort()
# timeit取得了平均值
# sort()在后续排序中会越来越快直到趋于稳定

736 µs ± 16.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
li = [random.random() for i in range(100000)]
%time li.sort()
# %time是用户感知的时间长

Wall time: 18 ms


In [21]:
%time li.sort()

Wall time: 2.02 ms


In [22]:
%time li.sort()

Wall time: 1.99 ms


In [24]:
%%html
<div class="test">html content</div>

In [25]:
%%js
document.querySelector('.test').innerHTML="我成功了"

<IPython.core.display.Javascript object>

In [1]:
%%writefile wr.py
import random
li = [random.random() for i in range(100000)]

Overwriting wr.py


## Python list
1. list长度不固定
2. list类型不固定

In [3]:
li = list(range(10))
li[5] = 'hello'
li

[0, 1, 2, 3, 4, 'hello', 6, 7, 8, 9]

## Python array
1. array类型固定
2. array长度不固定，可以插入

In [4]:
import array
arr = array.array('i', list(range(10)))
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5] = "hello"

TypeError: an integer is required (got type str)

### 为什么使用Numpy？
1. Python中提供了list容器，可以当作数组使用。但列表中的元素可以是任何对象，因此列表中保存的是对象的指针，这样一来，为了保存一个简单的列表[1,2,3]。就需要三个指针和三个整数对象。对于数值运算来说，这种结构显然不够高效。
2. Python虽然也提供了array模块，但其只支持一维数组，不支持多维数组(在TensorFlow里面偏向于矩阵理解)，也没有各种运算函数。因而不适合数值运算。
3. NumPy的出现弥补了这些不足。

In [8]:
import numpy as np
a = np.array(list(range(10))) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(a)

numpy.ndarray

In [11]:
a.dtype # 默认为int

dtype('int32')

In [12]:
b = np.array([1.0, 2, 3]) # 存在一个float，整个ndarry都为float
b.dtype

dtype('float64')

In [14]:
# 指定类型
c = np.array([1,2,3], dtype=float)
c

array([1., 2., 3.])

### 1. 方便处理多维度数组或者矩阵之间的运算
### 2. 在处理多为数组或者矩阵，运算效率高

In [15]:
def python_test(n):
    a = [i**2 for i in range(n)]
    b = [i**2 for i in range(n)]
    c = []
    for i in range(n):
        c.append(a[i] + b[i])
    return c
python_test(10)

[0, 2, 8, 18, 32, 50, 72, 98, 128, 162]

In [16]:
def numpy_test(n):
    a = np.arange(n) ** 2 # 1 * n 矩阵的平方运算
    b = np.arange(n) ** 2
    c = a + b # 矩阵的相加
    return c
numpy_test(10)

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162], dtype=int32)

### 矩阵运算的效率对比：array和numpy.array

In [17]:
%time res = python_test(10000000)

Wall time: 9.08 s


In [18]:
%time res = numpy_test(10000000)

Wall time: 229 ms


### numpy矩阵生成方式

In [19]:
np.array([1, 2, 3])

array([1, 2, 3])

In [20]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 起 止 步进
np.arange(2, 20, 0.5)

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. ,
       18.5, 19. , 19.5])

In [23]:
# np.zeros 初始化矩阵，内值全为0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
# zeros默认类型为float，dytpe设置为int
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# shape(页，页内行，页内列)，类型为int
np.zeros(shape=(2,3,5), dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [27]:
# np.ones 初始化矩阵，内值全为1
np.ones([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# np.full 初始化矩阵，内值全为指定数值
np.full((2,3), 99, dtype=int)

array([[99, 99, 99],
       [99, 99, 99]])

In [29]:
# np.linspace 等差数列
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
np.random.randint(0, 10, size = (2, 5))

array([[9, 1, 2, 5, 5],
       [4, 2, 7, 7, 9]])

In [31]:
# seed(x) x为随机数号码，同一个号码生成的随机数都是相同的
np.random.seed(10)
np.random.randint(1, 10, 5)

array([5, 1, 2, 1, 2])

In [32]:
np.random.randint(1, 10, 5) # 不使用种子

array([9, 1, 9, 7, 5])

In [33]:
np.random.seed(10) # 使用种子10
np.random.randint(1, 10, 5)

array([5, 1, 2, 1, 2])

In [34]:
np.random.random() # 0 - 1的浮点数

0.709208009843012

In [35]:
np.random.random((3, 5)) # 3行5列 0 - 1的浮点数

array([[0.26556613, 0.26360285, 0.15037787, 0.68381843, 0.81660184],
       [0.33607158, 0.89081653, 0.19812181, 0.03061665, 0.87761494],
       [0.72743551, 0.54088093, 0.13145815, 0.41366737, 0.77872881]])

In [37]:
A = np.ones(shape = (2, 3, 5))
A

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [38]:
A.ndim # 数组维度

3

In [39]:
A.shape # 数组形状

(2, 3, 5)

In [40]:
A.size # 数组大小

30

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
X = a.reshape(2, 5) 
Y = a.reshape(5, 2)
X,Y

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [50]:
Z = np.arange(30).reshape(2, 3, 5)
Z

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [51]:
Z[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
Z[-1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [53]:
Z[(0, 1)] # 不推荐Z[0][1]

array([5, 6, 7, 8, 9])

In [54]:
Z[0, 1] 

array([5, 6, 7, 8, 9])

### 切片

In [56]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[0:5] # 索引0-5，不含末尾5

array([0, 1, 2, 3, 4])

In [58]:
a[5:] # 索引5-末尾

array([5, 6, 7, 8, 9])

In [59]:
a[2::2] # 索引2开始至末尾，步进为2

array([2, 4, 6, 8])

In [60]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 多维的切片

In [61]:
Z

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [62]:
Z[:1,:2,:3] # 前一页 前两行 前三列

array([[[0, 1, 2],
        [5, 6, 7]]])

In [63]:
Z[:1,::2,::2] # 1.先前一页 2.步进为2取行 3.步进为2取列

array([[[ 0,  2,  4],
        [10, 12, 14]]])

In [65]:
Z_T = Z.T # 转置 2-3-5 =》 5-3-2
Z_T

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])

### 矩阵合并

In [66]:
x1 = np.array([[21, 168],
              [18, 187]])
x2 = np.array([[0], 
               [1]])
x = np.concatenate([x1,x2], axis = 1) # 默认axis=0按行合并，axis=1按列合并
x

array([[ 21, 168,   0],
       [ 18, 187,   1]])

### 聚合操作

In [67]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
np.sum(X)

105

In [69]:
np.max(X)

14

In [70]:
np.mean(X)

7.0

In [3]:
import numpy as np
Z = np.arange(30).reshape(2, 3, 5)
Z[:1,:2]

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [4]:
Z[:1]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [5]:
Z[:1,:2,:1]

array([[[0],
        [5]]])